version: '3.7'
services:
  api:
    container_name: disk-api-springboot-postgresql
    image: disk-api-springboot-postgresql
    build: ./
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always

  db:
    container_name: disk-api-postgres
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    restart: always